# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dontgomanual.com
title: Dontgomanual
email: contact@dontgomanual.com
author: Don't go manual
description: > # "Write an awesome description for your new site here.
  E-Retail advisor providing automated insights for SEO & SEA.
copyright: 'Copyright &copy; 2019 Dontgomanual. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
#
email: contact@dontgomanual.com
# social:
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap
#   - title: linkedin
#     url:
plugins:
  - jekyll-sitemap
